### ISSUE TITLE
Mixed up arguments in plot functions

### ISSUE THREAD

**Issue by Arnemd** [Rajat-dhyani/Stock-Price-Predictor#2]
You mixed the two arguments in the plot functions. The plot functions take as arguments (actual, prediction), but in the notebook you pluged in (prediction, actual). So actually the green line, that is lagging behind the more volatile line, is the prediction.

**Comment by Rajat-dhyani** [comment]
Hey, @Arnemd thank you for pointing out. Fixed that issue.
