### ISSUE TITLE
Get the Data Not working

### ISSUE THREAD

**Issue by DEMONDevelop** [Rajat-dhyani/Stock-Price-Predictor#6]
data = get_historical_data('INFY','2017-01-01','2017-06-30') # from January 1, 2005 to June 30, 2017
this line shows the error
ParserError: Error tokenizing data. C error: Expected 142 fields in line 10, saw 3661
please help me solve it

**Comment by Rajat-dhyani** [comment]
Its been long since I have worked on this project. Might be possible that API structure has changed and out put as well, hence you are seeing this error. You can modify your code accordingly
